/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlumnoRouteImport } from './routes/alumno'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as CompletarDatosRouteImport } from './routes/completar-datos'
import { Route as ComprobanteRouteImport } from './routes/comprobante'
import { Route as ConfirmarNombreRouteImport } from './routes/confirmar-nombre'
import { Route as MiDiaRouteImport } from './routes/mi-dia'
import { Route as PagoRouteImport } from './routes/pago'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as TalleresRouteImport } from './routes/talleres'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBitacoraRouteImport } from './routes/admin.bitacora'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminElegiblesRouteImport } from './routes/admin.elegibles'
import { Route as AdminMonitoreoRouteImport } from './routes/admin.monitoreo'
import { Route as AdminPadronRouteImport } from './routes/admin.padron'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminSoporteRouteImport } from './routes/admin.soporte'
import { Route as AdminTalleresRouteImport } from './routes/admin.talleres'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as CapturaIndexRouteImport } from './routes/captura.index'
import { Route as CapturaEscaneoRouteImport } from './routes/captura.escaneo'
import { Route as CapturaHistorialRouteImport } from './routes/captura.historial'
import { Route as CapturaTallerRouteImport } from './routes/captura.taller'
import { Route as FinancierosIndexRouteImport } from './routes/financieros.index'
import { Route as FinancierosCargaMasivaRouteImport } from './routes/financieros.carga-masiva'
import { Route as FinancierosConciliacionRouteImport } from './routes/financieros.conciliacion'
import { Route as FinancierosFichaRouteImport } from './routes/financieros.ficha'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalConstanciaRouteImport } from './routes/portal.constancia'
import { Route as PortalEstadoRouteImport } from './routes/portal.estado'
import { Route as PortalEvidenciasRouteImport } from './routes/portal.evidencias'
import { Route as PortalQrRouteImport } from './routes/portal.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoRoute = AlumnoRouteImport.update({
  id: '/alumno',
  path: '/alumno',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarDatosRoute = CompletarDatosRouteImport.update({
  id: '/completar-datos',
  path: '/completar-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprobanteRoute = ComprobanteRouteImport.update({
  id: '/comprobante',
  path: '/comprobante',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarNombreRoute = ConfirmarNombreRouteImport.update({
  id: '/confirmar-nombre',
  path: '/confirmar-nombre',
  getParentRoute: () => rootRouteImport,
} as any)
const MiDiaRoute = MiDiaRouteImport.update({
  id: '/mi-dia',
  path: '/mi-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoRoute = PagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const TalleresRoute = TalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBitacoraRoute = AdminBitacoraRouteImport.update({
  id: '/admin/bitacora',
  path: '/admin/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/admin/configuracion',
  path: '/admin/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminElegiblesRoute = AdminElegiblesRouteImport.update({
  id: '/admin/elegibles',
  path: '/admin/elegibles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoreoRoute = AdminMonitoreoRouteImport.update({
  id: '/admin/monitoreo',
  path: '/admin/monitoreo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPadronRoute = AdminPadronRouteImport.update({
  id: '/admin/padron',
  path: '/admin/padron',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/admin/reportes',
  path: '/admin/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSoporteRoute = AdminSoporteRouteImport.update({
  id: '/admin/soporte',
  path: '/admin/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTalleresRoute = AdminTalleresRouteImport.update({
  id: '/admin/talleres',
  path: '/admin/talleres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaIndexRoute = CapturaIndexRouteImport.update({
  id: '/captura/',
  path: '/captura/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaEscaneoRoute = CapturaEscaneoRouteImport.update({
  id: '/captura/escaneo',
  path: '/captura/escaneo',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaHistorialRoute = CapturaHistorialRouteImport.update({
  id: '/captura/historial',
  path: '/captura/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaTallerRoute = CapturaTallerRouteImport.update({
  id: '/captura/taller',
  path: '/captura/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancierosIndexRoute = FinancierosIndexRouteImport.update({
  id: '/financieros/',
  path: '/financieros/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancierosCargaMasivaRoute = FinancierosCargaMasivaRouteImport.update({
  id: '/financieros/carga-masiva',
  path: '/financieros/carga-masiva',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancierosConciliacionRoute = FinancierosConciliacionRouteImport.update({
  id: '/financieros/conciliacion',
  path: '/financieros/conciliacion',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancierosFichaRoute = FinancierosFichaRouteImport.update({
  id: '/financieros/ficha',
  path: '/financieros/ficha',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalConstanciaRoute = PortalConstanciaRouteImport.update({
  id: '/portal/constancia',
  path: '/portal/constancia',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEstadoRoute = PortalEstadoRouteImport.update({
  id: '/portal/estado',
  path: '/portal/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEvidenciasRoute = PortalEvidenciasRouteImport.update({
  id: '/portal/evidencias',
  path: '/portal/evidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalQrRoute = PortalQrRouteImport.update({
  id: '/portal/qr',
  path: '/portal/qr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRoute
  '/bienvenida': typeof BienvenidaRoute
  '/completar-datos': typeof CompletarDatosRoute
  '/comprobante': typeof ComprobanteRoute
  '/confirmar-nombre': typeof ConfirmarNombreRoute
  '/mi-dia': typeof MiDiaRoute
  '/pago': typeof PagoRoute
  '/registro': typeof RegistroRoute
  '/revision': typeof RevisionRoute
  '/talleres': typeof TalleresRoute
  '/admin/bitacora': typeof AdminBitacoraRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/elegibles': typeof AdminElegiblesRoute
  '/admin/monitoreo': typeof AdminMonitoreoRoute
  '/admin/padron': typeof AdminPadronRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/captura/escaneo': typeof CapturaEscaneoRoute
  '/captura/historial': typeof CapturaHistorialRoute
  '/captura/taller': typeof CapturaTallerRoute
  '/financieros/carga-masiva': typeof FinancierosCargaMasivaRoute
  '/financieros/conciliacion': typeof FinancierosConciliacionRoute
  '/financieros/ficha': typeof FinancierosFichaRoute
  '/portal/constancia': typeof PortalConstanciaRoute
  '/portal/estado': typeof PortalEstadoRoute
  '/portal/evidencias': typeof PortalEvidenciasRoute
  '/portal/qr': typeof PortalQrRoute
  '/admin/': typeof AdminIndexRoute
  '/captura/': typeof CapturaIndexRoute
  '/financieros/': typeof FinancierosIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRoute
  '/bienvenida': typeof BienvenidaRoute
  '/completar-datos': typeof CompletarDatosRoute
  '/comprobante': typeof ComprobanteRoute
  '/confirmar-nombre': typeof ConfirmarNombreRoute
  '/mi-dia': typeof MiDiaRoute
  '/pago': typeof PagoRoute
  '/registro': typeof RegistroRoute
  '/revision': typeof RevisionRoute
  '/talleres': typeof TalleresRoute
  '/admin/bitacora': typeof AdminBitacoraRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/elegibles': typeof AdminElegiblesRoute
  '/admin/monitoreo': typeof AdminMonitoreoRoute
  '/admin/padron': typeof AdminPadronRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/captura/escaneo': typeof CapturaEscaneoRoute
  '/captura/historial': typeof CapturaHistorialRoute
  '/captura/taller': typeof CapturaTallerRoute
  '/financieros/carga-masiva': typeof FinancierosCargaMasivaRoute
  '/financieros/conciliacion': typeof FinancierosConciliacionRoute
  '/financieros/ficha': typeof FinancierosFichaRoute
  '/portal/constancia': typeof PortalConstanciaRoute
  '/portal/estado': typeof PortalEstadoRoute
  '/portal/evidencias': typeof PortalEvidenciasRoute
  '/portal/qr': typeof PortalQrRoute
  '/admin': typeof AdminIndexRoute
  '/captura': typeof CapturaIndexRoute
  '/financieros': typeof FinancierosIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRoute
  '/bienvenida': typeof BienvenidaRoute
  '/completar-datos': typeof CompletarDatosRoute
  '/comprobante': typeof ComprobanteRoute
  '/confirmar-nombre': typeof ConfirmarNombreRoute
  '/mi-dia': typeof MiDiaRoute
  '/pago': typeof PagoRoute
  '/registro': typeof RegistroRoute
  '/revision': typeof RevisionRoute
  '/talleres': typeof TalleresRoute
  '/admin/bitacora': typeof AdminBitacoraRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/elegibles': typeof AdminElegiblesRoute
  '/admin/monitoreo': typeof AdminMonitoreoRoute
  '/admin/padron': typeof AdminPadronRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/captura/escaneo': typeof CapturaEscaneoRoute
  '/captura/historial': typeof CapturaHistorialRoute
  '/captura/taller': typeof CapturaTallerRoute
  '/financieros/carga-masiva': typeof FinancierosCargaMasivaRoute
  '/financieros/conciliacion': typeof FinancierosConciliacionRoute
  '/financieros/ficha': typeof FinancierosFichaRoute
  '/portal/constancia': typeof PortalConstanciaRoute
  '/portal/estado': typeof PortalEstadoRoute
  '/portal/evidencias': typeof PortalEvidenciasRoute
  '/portal/qr': typeof PortalQrRoute
  '/admin/': typeof AdminIndexRoute
  '/captura/': typeof CapturaIndexRoute
  '/financieros/': typeof FinancierosIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumno'
    | '/bienvenida'
    | '/completar-datos'
    | '/comprobante'
    | '/confirmar-nombre'
    | '/mi-dia'
    | '/pago'
    | '/registro'
    | '/revision'
    | '/talleres'
    | '/admin/bitacora'
    | '/admin/configuracion'
    | '/admin/elegibles'
    | '/admin/monitoreo'
    | '/admin/padron'
    | '/admin/reportes'
    | '/admin/soporte'
    | '/admin/talleres'
    | '/admin/usuarios'
    | '/captura/escaneo'
    | '/captura/historial'
    | '/captura/taller'
    | '/financieros/carga-masiva'
    | '/financieros/conciliacion'
    | '/financieros/ficha'
    | '/portal/constancia'
    | '/portal/estado'
    | '/portal/evidencias'
    | '/portal/qr'
    | '/admin/'
    | '/captura/'
    | '/financieros/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumno'
    | '/bienvenida'
    | '/completar-datos'
    | '/comprobante'
    | '/confirmar-nombre'
    | '/mi-dia'
    | '/pago'
    | '/registro'
    | '/revision'
    | '/talleres'
    | '/admin/bitacora'
    | '/admin/configuracion'
    | '/admin/elegibles'
    | '/admin/monitoreo'
    | '/admin/padron'
    | '/admin/reportes'
    | '/admin/soporte'
    | '/admin/talleres'
    | '/admin/usuarios'
    | '/captura/escaneo'
    | '/captura/historial'
    | '/captura/taller'
    | '/financieros/carga-masiva'
    | '/financieros/conciliacion'
    | '/financieros/ficha'
    | '/portal/constancia'
    | '/portal/estado'
    | '/portal/evidencias'
    | '/portal/qr'
    | '/admin'
    | '/captura'
    | '/financieros'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/alumno'
    | '/bienvenida'
    | '/completar-datos'
    | '/comprobante'
    | '/confirmar-nombre'
    | '/mi-dia'
    | '/pago'
    | '/registro'
    | '/revision'
    | '/talleres'
    | '/admin/bitacora'
    | '/admin/configuracion'
    | '/admin/elegibles'
    | '/admin/monitoreo'
    | '/admin/padron'
    | '/admin/reportes'
    | '/admin/soporte'
    | '/admin/talleres'
    | '/admin/usuarios'
    | '/captura/escaneo'
    | '/captura/historial'
    | '/captura/taller'
    | '/financieros/carga-masiva'
    | '/financieros/conciliacion'
    | '/financieros/ficha'
    | '/portal/constancia'
    | '/portal/estado'
    | '/portal/evidencias'
    | '/portal/qr'
    | '/admin/'
    | '/captura/'
    | '/financieros/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumnoRoute: typeof AlumnoRoute
  BienvenidaRoute: typeof BienvenidaRoute
  CompletarDatosRoute: typeof CompletarDatosRoute
  ComprobanteRoute: typeof ComprobanteRoute
  ConfirmarNombreRoute: typeof ConfirmarNombreRoute
  MiDiaRoute: typeof MiDiaRoute
  PagoRoute: typeof PagoRoute
  RegistroRoute: typeof RegistroRoute
  RevisionRoute: typeof RevisionRoute
  TalleresRoute: typeof TalleresRoute
  AdminBitacoraRoute: typeof AdminBitacoraRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminElegiblesRoute: typeof AdminElegiblesRoute
  AdminMonitoreoRoute: typeof AdminMonitoreoRoute
  AdminPadronRoute: typeof AdminPadronRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminSoporteRoute: typeof AdminSoporteRoute
  AdminTalleresRoute: typeof AdminTalleresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  CapturaEscaneoRoute: typeof CapturaEscaneoRoute
  CapturaHistorialRoute: typeof CapturaHistorialRoute
  CapturaTallerRoute: typeof CapturaTallerRoute
  FinancierosCargaMasivaRoute: typeof FinancierosCargaMasivaRoute
  FinancierosConciliacionRoute: typeof FinancierosConciliacionRoute
  FinancierosFichaRoute: typeof FinancierosFichaRoute
  PortalConstanciaRoute: typeof PortalConstanciaRoute
  PortalEstadoRoute: typeof PortalEstadoRoute
  PortalEvidenciasRoute: typeof PortalEvidenciasRoute
  PortalQrRoute: typeof PortalQrRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CapturaIndexRoute: typeof CapturaIndexRoute
  FinancierosIndexRoute: typeof FinancierosIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumno': {
      id: '/alumno'
      path: '/alumno'
      fullPath: '/alumno'
      preLoaderRoute: typeof AlumnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-datos': {
      id: '/completar-datos'
      path: '/completar-datos'
      fullPath: '/completar-datos'
      preLoaderRoute: typeof CompletarDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprobante': {
      id: '/comprobante'
      path: '/comprobante'
      fullPath: '/comprobante'
      preLoaderRoute: typeof ComprobanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-nombre': {
      id: '/confirmar-nombre'
      path: '/confirmar-nombre'
      fullPath: '/confirmar-nombre'
      preLoaderRoute: typeof ConfirmarNombreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-dia': {
      id: '/mi-dia'
      path: '/mi-dia'
      fullPath: '/mi-dia'
      preLoaderRoute: typeof MiDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago': {
      id: '/pago'
      path: '/pago'
      fullPath: '/pago'
      preLoaderRoute: typeof PagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talleres': {
      id: '/talleres'
      path: '/talleres'
      fullPath: '/talleres'
      preLoaderRoute: typeof TalleresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bitacora': {
      id: '/admin/bitacora'
      path: '/admin/bitacora'
      fullPath: '/admin/bitacora'
      preLoaderRoute: typeof AdminBitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elegibles': {
      id: '/admin/elegibles'
      path: '/admin/elegibles'
      fullPath: '/admin/elegibles'
      preLoaderRoute: typeof AdminElegiblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoreo': {
      id: '/admin/monitoreo'
      path: '/admin/monitoreo'
      fullPath: '/admin/monitoreo'
      preLoaderRoute: typeof AdminMonitoreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/padron': {
      id: '/admin/padron'
      path: '/admin/padron'
      fullPath: '/admin/padron'
      preLoaderRoute: typeof AdminPadronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/soporte': {
      id: '/admin/soporte'
      path: '/admin/soporte'
      fullPath: '/admin/soporte'
      preLoaderRoute: typeof AdminSoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/talleres': {
      id: '/admin/talleres'
      path: '/admin/talleres'
      fullPath: '/admin/talleres'
      preLoaderRoute: typeof AdminTalleresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura/': {
      id: '/captura/'
      path: '/captura'
      fullPath: '/captura/'
      preLoaderRoute: typeof CapturaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura/escaneo': {
      id: '/captura/escaneo'
      path: '/captura/escaneo'
      fullPath: '/captura/escaneo'
      preLoaderRoute: typeof CapturaEscaneoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura/historial': {
      id: '/captura/historial'
      path: '/captura/historial'
      fullPath: '/captura/historial'
      preLoaderRoute: typeof CapturaHistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura/taller': {
      id: '/captura/taller'
      path: '/captura/taller'
      fullPath: '/captura/taller'
      preLoaderRoute: typeof CapturaTallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financieros/': {
      id: '/financieros/'
      path: '/financieros'
      fullPath: '/financieros/'
      preLoaderRoute: typeof FinancierosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financieros/carga-masiva': {
      id: '/financieros/carga-masiva'
      path: '/financieros/carga-masiva'
      fullPath: '/financieros/carga-masiva'
      preLoaderRoute: typeof FinancierosCargaMasivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financieros/conciliacion': {
      id: '/financieros/conciliacion'
      path: '/financieros/conciliacion'
      fullPath: '/financieros/conciliacion'
      preLoaderRoute: typeof FinancierosConciliacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financieros/ficha': {
      id: '/financieros/ficha'
      path: '/financieros/ficha'
      fullPath: '/financieros/ficha'
      preLoaderRoute: typeof FinancierosFichaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/constancia': {
      id: '/portal/constancia'
      path: '/portal/constancia'
      fullPath: '/portal/constancia'
      preLoaderRoute: typeof PortalConstanciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/estado': {
      id: '/portal/estado'
      path: '/portal/estado'
      fullPath: '/portal/estado'
      preLoaderRoute: typeof PortalEstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/evidencias': {
      id: '/portal/evidencias'
      path: '/portal/evidencias'
      fullPath: '/portal/evidencias'
      preLoaderRoute: typeof PortalEvidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/qr': {
      id: '/portal/qr'
      path: '/portal/qr'
      fullPath: '/portal/qr'
      preLoaderRoute: typeof PortalQrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumnoRoute: AlumnoRoute,
  BienvenidaRoute: BienvenidaRoute,
  CompletarDatosRoute: CompletarDatosRoute,
  ComprobanteRoute: ComprobanteRoute,
  ConfirmarNombreRoute: ConfirmarNombreRoute,
  MiDiaRoute: MiDiaRoute,
  PagoRoute: PagoRoute,
  RegistroRoute: RegistroRoute,
  RevisionRoute: RevisionRoute,
  TalleresRoute: TalleresRoute,
  AdminBitacoraRoute: AdminBitacoraRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminElegiblesRoute: AdminElegiblesRoute,
  AdminMonitoreoRoute: AdminMonitoreoRoute,
  AdminPadronRoute: AdminPadronRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminSoporteRoute: AdminSoporteRoute,
  AdminTalleresRoute: AdminTalleresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  CapturaEscaneoRoute: CapturaEscaneoRoute,
  CapturaHistorialRoute: CapturaHistorialRoute,
  CapturaTallerRoute: CapturaTallerRoute,
  FinancierosCargaMasivaRoute: FinancierosCargaMasivaRoute,
  FinancierosConciliacionRoute: FinancierosConciliacionRoute,
  FinancierosFichaRoute: FinancierosFichaRoute,
  PortalConstanciaRoute: PortalConstanciaRoute,
  PortalEstadoRoute: PortalEstadoRoute,
  PortalEvidenciasRoute: PortalEvidenciasRoute,
  PortalQrRoute: PortalQrRoute,
  AdminIndexRoute: AdminIndexRoute,
  CapturaIndexRoute: CapturaIndexRoute,
  FinancierosIndexRoute: FinancierosIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
